### ISSUE TITLE
Unable to use package with Framework 4.5.2

### ISSUE THREAD

**Issue by CaverGirl** [lecode-official/deepl-dotnet#15] opened 2022-01-27 06:01 UTC
Hello!

I'm trying to install the Nuget Package into my VB.NET Framework 4.5.2.
When I try to do that, the Nuget Package Manager says:

Could not install package 'DeepL 0.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

On stackoverflow, one suggestion was to rename the lib folder:

So I changed the folder 
C:\Users\MyUser\.nuget\packages\deepl\0.3.0\lib\netstandard2.0
to 
C:\Users\MyUser\.nuget\packages\deepl\0.3.0\lib\net45

Then I could install the package, but when I try to run the program, I get the following error:

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=File or Assembly not found: "Microsoft.AspNetCore.StaticFiles, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"was not found
  Source=DeepL
  StackTrace:
   at DeepL.DeepLClient..ctor(String authenticationKey, Boolean useFreeApi)
   at tws.modDeepL.VB$StateMachine_0_TranslateDeepL.MoveNext() 

When I try to install Microsoft.AspNetCore.StaticFiles 2.2.0, it says "Could not install package 'Microsoft.AspNetCore.StaticFiles 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."				

I have also renamed this folder. 
And now I get the error "Newtonsoft.Json version 12.0.0.0" was not found.
Argh.

**Comment by CaverGirl** [comment] 2022-01-27 06:17
Edit: I installed it from nuget, now it works.
But why is it so difficult?

Thanks!

**Comment by lecode-official** [comment] 2022-01-27 19:43
Hi CaverGirl,

I am afraid this is by design. I am targeting `netstandard2.0`, which is only supported by the .NET Framework from 4.6.1 on. You can find a complete compatibility list for the .NET Standard [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0).

But I am still curious how you actually managed to get it to run. Would you mind sharing your installation steps?

Is it possible for you to upgrade to a later version of the .NET Framework? Especially, considering, that 4.5.2 is only supported until [April 26, 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework) (in fact, 4.6 and 4.6.1 are also being retired on the same day). Also, Microsoft is not recommending to target any .NET Standard version below `netstandard2.0`.

I am sorry to disappoint you, but this problem won't be fixed.

Best regards
David

**Comment by lecode-official** [comment] 2022-02-01 21:02
Hi CaverGirl,

since I am not going to fix this, as .NET 4.5.2 will reach end-of-support in April, I am going to close this issue for now. If there is still something I can do for you, please feel free to reopen this issue or create a new one.

**Closed as completed by lecode-official** 2022-02-01 21:02 UTC
Labels: wontfix
